### ISSUE TITLE
Síntesis de calidad de software 

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Abraham890#1]
[Abraham_Reyes_Ortiz_sintesis-de-calidad.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Abraham890/files/9569368/Abraham_Reyes_Ortiz_sintesis-de-calidad.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
